"""
Assemble the rclone --filter-from file.

rclone evaluates rules top-to-bottom, first match wins, and anything matching no
rule is INCLUDED by default. Ordering (highest priority first):

  0. User .backupignore patterns     (explicit user intent)
  1. Per-repo .git excludes          (clean/pushed repos only)
  2. Global junk dirs                (node_modules, .venv, etc)
  3. Global junk files               (*.log, .DS_Store, etc)
  4. (implicit) include everything else

No trailing '- **:': the fallthrough-include is intentional so that KEEP repos'
.git (which have no exclude rule) is carried along. Whole-directory drops via
.backupignore-all are handled by --exclude-if-present in the runner, not here.
"""

from pathlib import Path

from devsync.filtering.backupignore import collect_rules
from devsync.git.audit import GitDecision, RepoStatus

DEFAULT_JUNK_DIRS = [
    "node_modules",
    ".venv",
    "venv",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".ipynb_checkpoints",
    "target",
    ".gradle",
    ".next",
    ".turbo",
    "dist",
    "build",
    ".cache",
    ".terraform",
]

DEFAULT_JUNK_FILES = [
    "*.pyc",
    "*.pyo",
    "*.log",
    ".DS_Store",
    "Thumbs.db",
    "*.tmp",
    "*.swp",
]


def build_filter_lines(
    root: Path, repos: list[RepoStatus], junk_dirs: list[str] | None = None, junk_files: list[str] | None = None
) -> list[str]:
    junk_dirs = junk_dirs if junk_dirs is not None else DEFAULT_JUNK_DIRS
    junk_files = junk_files if junk_files is not None else DEFAULT_JUNK_FILES

    lines: list[str] = ["# Auto-generated by devsync; do not edit manually", ""]

    ignore_rules, marker_dirs = collect_rules(root)

    if ignore_rules:
        lines.append("# User .backupignore patterns")
        lines.extend(ignore_rules)
        lines.append("")

    if marker_dirs:
        lines.append("# Dirs with a .backupignore-all marker (excluded via --exclude-if-present in the runner)")
        lines.extend(f"#    {d}" for d in marker_dirs)
        lines.append("")

    excludable = [s for s in repos if s.decision == GitDecision.EXCLUDE_GIT]

    if excludable:
        lines.append("# .git excluded for clean, fully-pushed repos")

        for s in excludable:
            rel = s.path.relative_to(root).as_posix()
            anchor = "" if rel == "." else f"/{rel}"
            lines.append(f"- {anchor}/.git/**")
        lines.append("")

    lines.append("# Global junk dirs")
    lines.extend(f"- {d}/**" for d in junk_dirs)
    lines.append("")

    lines.append("# Global junk files")
    lines.extend(f"- {f}" for f in junk_files)
    lines.append("")

    lines.append("# Everything else is included by rclone's default fallthrough")
    return lines


def write_filter_file(path: Path, lines: list[str]) -> None:
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
